print("my name is dennis,")
print("am 21 years old  of age,")
print("i like doing mathematics.")
print("am doing bachelor of mathematics in taita taveta university")
print("happy birthday to you mum,")
print("How old are you now,")
print("Conratulation mum for attaining 40 years.")
print("lots of love for you mum,")
print("enjoy your day.")
print("thanks to our grandmother,")
print("for blessing us with you mum")